apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: generator-bq-latency
  labels:
    service_name: generator
    feature_name: bq
    slo_name: latency
    metadata:
      env: test
spec:
  description: >
    99% of BigQuery API HTTP response latencies < 400ms
  backend: cloud_monitoring
  method: distribution_cut
  exporters:
  - bigquery
  - cloud_monitoring
  - pubsub
  service_level_indicator:
    filter_valid: >
      metric.type="serviceruntime.googleapis.com/api/request_latencies"
      resource.type="consumed_api"
      resource.label."project_id"="${PROJECT_ID}"
      resource.label."service"="bigquery.googleapis.com"
    good_below_threshold: true
    threshold_bucket: 17
  goal: 0.99
